export const FETCH_GIPHY_DATA = 'FETCH_GIPHY_DATA';
export const FETCH_GIPHY_DATA_FAIL = 'FETCH_GIPHY_DATA_FAIL';
export const FETCH_GIPHY_DATA_SUCCESS = 'FETCH_GIPHY_DATA_SUCCESS';
export const FETCH_GIPHY_LOAD_MORE = 'FETCH_GIPHY_LOAD_MORE';
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const TOGGLE_SHOW_PROFILE = 'TOGGLE_SHOW_PROFILE';
